"""Match table

Revision ID: 128fc580b95a
Revises: 
Create Date: 2023-11-07 06:56:14.538094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128fc580b95a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(length=64), nullable=True),
    sa.Column('timestamp_start', sa.Integer(), nullable=True),
    sa.Column('timestamp_update', sa.Integer(), nullable=True),
    sa.Column('round_wins', sa.Integer(), nullable=True),
    sa.Column('round_losses', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('mvps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_map_name'), ['map_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_steam_id'), ['steam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_steam_id'))
        batch_op.drop_index(batch_op.f('ix_match_map_name'))

    op.drop_table('match')
    # ### end Alembic commands ###
