"""Changed match table

Revision ID: 2f78c1e24120
Revises: 128fc580b95a
Create Date: 2023-11-07 22:19:50.128229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f78c1e24120'
down_revision = '128fc580b95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steamid', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('player_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('map_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('map_phase', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_match_steam_id')
        batch_op.create_index(batch_op.f('ix_match_map_id'), ['map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_steamid'), ['steamid'], unique=False)
        batch_op.drop_column('steam_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_id', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_match_steamid'))
        batch_op.drop_index(batch_op.f('ix_match_map_id'))
        batch_op.create_index('ix_match_steam_id', ['steam_id'], unique=False)
        batch_op.drop_column('map_phase')
        batch_op.drop_column('map_id')
        batch_op.drop_column('player_name')
        batch_op.drop_column('steamid')

    # ### end Alembic commands ###
