"""empty message

Revision ID: 33cd98d67397
Revises: be5751348202
Create Date: 2023-11-06 13:52:40.816396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cd98d67397'
down_revision = 'be5751348202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_match_map_name'), ['map_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_steam_id'), ['steam_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_steam_id'))
        batch_op.drop_index(batch_op.f('ix_match_map_name'))
        batch_op.drop_column('map_name')

    # ### end Alembic commands ###
