"""empty message

Revision ID: 36da220bf8a8
Revises: ccf141e4847d
Create Date: 2023-11-06 17:43:30.196181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36da220bf8a8'
down_revision = 'ccf141e4847d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp_update', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mvps', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_match_match_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('mvp')
        batch_op.drop_column('match_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mvp', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_match_match_id', ['match_id'], unique=False)
        batch_op.drop_column('mvps')
        batch_op.drop_column('timestamp_update')
        batch_op.drop_column('timestamp_start')

    # ### end Alembic commands ###
