"""Change from LAN stats to Match table

Revision ID: be5751348202
Revises: fd7008fac75b
Create Date: 2023-11-06 13:44:38.113624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5751348202'
down_revision = 'fd7008fac75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.Column('round_wins', sa.Integer(), nullable=True),
    sa.Column('round_losses', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('mvp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.drop_table('lan_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lan_stats',
    sa.Column('steam_id', sa.INTEGER(), nullable=False),
    sa.Column('games', sa.INTEGER(), nullable=True),
    sa.Column('wins', sa.INTEGER(), nullable=True),
    sa.Column('losses', sa.INTEGER(), nullable=True),
    sa.Column('rounds', sa.INTEGER(), nullable=True),
    sa.Column('kills', sa.INTEGER(), nullable=True),
    sa.Column('assists', sa.INTEGER(), nullable=True),
    sa.Column('deaths', sa.INTEGER(), nullable=True),
    sa.Column('dmg_done', sa.INTEGER(), nullable=True),
    sa.Column('mvp', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.drop_table('match')
    # ### end Alembic commands ###
